const descriptions = [
    { key: "ABS", value: "Anti-lock Braking System helps prevent skidding during emergency braking." },
    { key: "Air Suspension", value: "System that adjusts ride height for comfort and stability." },
    { key: "Airbag Indicator Light", value: "Notifies if there's an issue with the airbag system." },
    { key: "Automatic Gearbox Warning", value: "Alerts about issues with the automatic transmission." },
    { key: "Automatic Shift Lock or Engine Start Indicator Light", value: "Indicates problems with starting or shifting gears." },
    { key: "Battery Alert Light", value: "Warns of battery charging system issues." },
    { key: "Brake Warning Light", value: "Alerts when there's an issue with the braking system." },
    { key: "Check Engine Light", value: "Indicates a problem with the engine or emissions system." },
    { key: "Coolant Temperature Warning Light", value: "Warns of engine overheating due to coolant issues." },
    { key: "DPF light", value: "Diesel Particulate Filter alerts for issues with diesel exhaust emissions." },
    { key: "Eco Driving Indicator", value: "Promotes fuel-efficient driving habits." },
    { key: "Engine Temperature Warning Light", value: "Signals engine temperature abnormalities." },
    { key: "Fog Lamp Indicator Light", value: "Alerts when fog lights are turned on." },
    { key: "Glow Plug Indicator", value: "Indicates glow plug operation in diesel engines." },
    { key: "Lamp Out", value: "Warns of a faulty exterior light." },
    { key: "Lane Departure Warning Light", value: "Notifies when the vehicle deviates from its lane without signaling." },
    { key: "Low Fuel Indicator Light", value: "Warns when fuel level is low." },
    { key: "OD", value: "Overdrive indicates the transmission is in high gear for fuel efficiency." },
    { key: "Oil", value: "Indicates low engine oil pressure or low oil level." },
    { key: "Power Steering Warning Light", value: "Alerts to power steering system issues." },
    { key: "Seat Belt Reminder Light", value: "Reminds to fasten seat belts for safety." },
    { key: "Security Indicator Light", value: "Indicates the vehicle's security system status." },
    { key: "Steering Wheel Lock", value: "Notifies when the steering wheel is locked." },
    { key: "Tire", value: "Alerts for low tire pressure or other tire-related issues." },
    { key: "Traction Control Light", value: "Indicates traction control system is active." },
    { key: "Traction Control Malfunction Light", value: "Warns of malfunction in traction control system." },
    { key: "Trailer Tow Hitch Warning", value: "Alerts when towing hitch is not properly connected." },
    { key: "Transmission Temperature Warning Light", value: "Warns of high transmission fluid temperature." },
    { key: "Washer Fluid Indicator Light", value: "Indicates low windshield washer fluid level." }
];
module.exports = descriptions;
